from tkinter import *

window = Tk()
window.resizable(0,0)
window.title("Programación II - Sistema Stock - Super Rugby")
window.geometry('775x543')


#Cuadros Esteticos
cuadro_lapiz = Canvas(window, width=378, height=212, borderwidth=2, bg='#EEEEEE', relief='raised').place(x=0, y=10)
cuadro_aspirina = Canvas(window, width=378, height=212, borderwidth=2, bg='#EEEEEE', relief='raised').place(x=390, y=10)
cuadro_lapiz = Canvas(window, width=378, height=212, borderwidth=2, bg='#EEEEEE', relief='raised').place(x=0, y=240)
cuadro_pan = Canvas(window, width=378, height=212, borderwidth=2, bg='#EEEEEE', relief='raised').place(x=390, y=240)
cuadro_opciones = Canvas(window, width=768, height=65, borderwidth=2, bg='#EEEEEE', relief='raised').place(x=0, y=470)

#Productos
    #Lapiz
lapiz = Label(window, text="Lapiz", font="Arial")
lapiz.place(x=0, y=0)
tipo = Label(window, text="Tipo:", font=("Arial", 11))
tipo.place(x=90, y=25)
cantidad = Label(window, text="Cantidad Bodega:", font=("Arial", 11))
cantidad.place(x=90, y=55)
valor = Label(window, text="Valor Unitario:", font=("Arial", 11))
valor.place(x=90, y=85)
vendidas = Label(window, text="Cantidad Vendidas:", font=("Arial", 11))
vendidas.place(x=90, y=115)
minima = Label(window, text="Cantidad Minima:", font=("Arial", 11))
minima.place(x=90, y=145)
    #Aspirina
aspirina = Label(window, text="Aspirina", font="Arial")
aspirina.place(x=390, y=0)
tipo1 = Label(window, text="Tipo:", font=("Arial", 11))
tipo1.place(x=480, y=25)
cantidad1 = Label(window, text="Cantidad Bodega:", font=("Arial", 11))
cantidad1.place(x=480, y=55)
valor1 = Label(window, text="Valor Unitario:", font=("Arial", 11))
valor1.place(x=480, y=85)
vendidas1 = Label(window, text="Cantidad Vendidas:", font=("Arial", 11))
vendidas1.place(x=480, y=115)
minima1 = Label(window, text="Cantidad Minima:", font=("Arial", 11))
minima1.place(x=480, y=145)
    #Borrador
borrador = Label(window, text="Borrador", font="Arial")
borrador.place(x=0, y=230)
tipo2 = Label(window, text="Tipo:", font=("Arial", 11))
tipo2.place(x=90, y=255)
cantidad2 = Label(window, text="Cantidad Bodega:", font=("Arial", 11))
cantidad2.place(x=90, y=285)
valor2 = Label(window, text="Valor Unitario:", font=("Arial", 11))
valor2.place(x=90, y=315)
vendidas2 = Label(window, text="Cantidad Vendidas:", font=("Arial", 11))
vendidas2.place(x=90, y=345)
minima2 = Label(window, text="Cantidad Minima:", font=("Arial", 11))
minima2.place(x=90, y=375)
    #Pan
pan = Label(window, text="Pan", font="Arial")
pan.place(x=390, y=230)
tipo3 = Label(window, text="Tipo:", font=("Arial", 11))
tipo3.place(x=480, y=255)
cantidad3 = Label(window, text="Cantidad Bodega:", font=("Arial", 11))
cantidad3.place(x=480, y=285)
valor3 = Label(window, text="Valor Unitario:", font=("Arial", 11))
valor3.place(x=480, y=315)
vendidas3 = Label(window, text="Cantidad Vendidas:", font=("Arial", 11))
vendidas3.place(x=480, y=345)
minima3 = Label(window, text="Cantidad Minima:", font=("Arial", 11))
minima3.place(x=480, y=375)

#Productos Variables
    #Lapiz
valor_tipo = Label(window, text="Papeleria", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_tipo.place(x=230, y=25)
valor_cantidad = Label(window, text="18", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_cantidad.place(x=230, y=55)
valor_valor = Label(window, text="20.0", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_valor.place(x=230, y=85)
valor_vendidas = Label(window, text="0", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_vendidas.place(x=230, y=115)
valor_minima = Label(window, text="5", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_minima.place(x=230, y=145)
    #Aspirina
valor_tipo1 = Label(window, text="Drogueria", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_tipo1.place(x=620, y=25)
valor_cantidad1 = Label(window, text="25", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_cantidad1.place(x=620, y=55)
valor_valor1 = Label(window, text="50.0", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_valor1.place(x=620, y=85)
valor_vendidas1 = Label(window, text="0", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_vendidas1.place(x=620, y=115)
valor_minima1 = Label(window, text="8", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_minima1.place(x=620, y=145)
    #Borrador
valor_tipo2 = Label(window, text="Papeleria", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_tipo2.place(x=230, y=255)
valor_cantidad2 = Label(window, text="30", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_cantidad2.place(x=230, y=285)
valor_valor2 = Label(window, text="10.0", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_valor2.place(x=230, y=315)
valor_vendidas2 = Label(window, text="0", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_vendidas2.place(x=230, y=345)
valor_minima2 = Label(window, text="10", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_minima2.place(x=230, y=375)
    #Pan
valor_tipo3 = Label(window, text="Supermercado", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_tipo3.place(x=620, y=255)
valor_cantidad3 = Label(window, text="15", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_cantidad3.place(x=620, y=285)
valor_valor3 = Label(window, text="45.0", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_valor3.place(x=620, y=315)
valor_vendidas3 = Label(window, text="0", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_vendidas3.place(x=620, y=345)
valor_minima3 = Label(window, text="20", font=("Arial", 11), borderwidth=2, width=14, relief="groove")
valor_minima3.place(x=620, y=375)

#Botones
    #Lapiz
abastecer = Button(window, text="Abastecer", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
abastecer.place(x=10, y=190)
vender = Button(window, text="Vender", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
vender.place(x=135, y=190)
cambiar = Button(window, text="Cambiar", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
cambiar.place(x=260, y=190)
    #Aspirina
abastecer1 = Button(window, text="Abastecer", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
abastecer1.place(x=400, y=190)
vender1 = Button(window, text="Vender", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
vender1.place(x=525, y=190)
cambiar1 = Button(window, text="Cambiar", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
cambiar1.place(x=650, y=190)
    #Borrador
abastecer2 = Button(window, text="Abastecer", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
abastecer2.place(x=10, y=420)
vender2 = Button(window, text="Vender", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
vender2.place(x=135, y=420)
cambiar2 = Button(window, text="Cambiar", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
cambiar2.place(x=260, y=420)
    #Pan
abastecer3 = Button(window, text="Abastecer", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
abastecer3.place(x=400, y=420)
vender3 = Button(window, text="Vender", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
vender3.place(x=525, y=420)
cambiar3 = Button(window, text="Cambiar", font=("Arial", 10), width = 13, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
cambiar3.place(x=650, y=420)

#Opciones
opciones = Label(window, text="Opciones", font="Arial").place(x=0, y=460)
mas_vendido = Button(window, text="Producto Mas Vendido", font=("Arial", 10), width = 19, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
mas_vendido.place(x=50, y=490)
menos_vendido = Button(window, text="Producto Menos Vendido", font=("Arial", 10), width = 19, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
menos_vendido.place(x=220, y=490)
ventas = Button(window, text="Promedio Ventas", font=("Arial", 10), width = 19, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
ventas.place(x=390, y=490)
caja = Button(window, text="Dinero En Caja", font=("Arial", 10), width = 19, borderwidth=2, relief="raised", bg="#EEEEEE", cursor="hand2")
caja.place(x=560, y=490)

window.mainloop()
